# Generated by Django 4.1.3 on 2023-02-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="date_created",),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
