# Generated by Django 4.1.3 on 2023-02-18 03:46

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_user_projects_user_projects"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="projects",),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("nodes", jsonfield.fields.JSONField()),
                ("edges", jsonfield.fields.JSONField()),
                ("data", jsonfield.fields.JSONField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.project"
                    ),
                ),
            ],
        ),
    ]
