# Generated by Django 4.1.3 on 2023-02-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_script_owner"),
    ]

    operations = [
        migrations.DeleteModel(name="Script",),
    ]
